
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/applicationdb
    username: root
    password: AAaa@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

  application:
    name: Application Management App



